name: 'build_cornes_plus_8v_bt'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      alphas: '["qwerty"]'
      board: '["nice_nano//zmk"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
